# Generated by Django 3.2.5 on 2023-01-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommCd',
            fields=[
                ('comm_cd', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hi_comm_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('cd_nm', models.CharField(max_length=100)),
                ('cd_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('etc_1', models.CharField(blank=True, max_length=100, null=True)),
                ('etc_2', models.CharField(blank=True, max_length=100, null=True)),
                ('etc_3', models.CharField(blank=True, max_length=100, null=True)),
                ('alias_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('modf_dt', models.DateTimeField(auto_now=True, null=True)),
                ('reg_mem_no', models.IntegerField(blank=True, null=True)),
                ('modf_mem_no', models.IntegerField(blank=True, null=True)),
                ('del_yn', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'comm_cd',
                'managed': False,
            },
        ),
    ]
