# Generated by Django 3.2.5 on 2023-01-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_code', models.CharField(default='CC', max_length=2)),
                ('upper_code', models.CharField(max_length=8)),
                ('lower_code', models.CharField(max_length=8)),
            ],
            options={
                'ordering': ['upper_code'],
            },
        ),
    ]
