# Generated by Django 3.2.5 on 2023-01-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_ccode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CC2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_code', models.CharField(default='', max_length=8)),
                ('parent_code', models.CharField(blank=True, max_length=8)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('del_yn', models.CharField(default='N', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.CharField(max_length=11)),
                ('modified_user', models.CharField(max_length=11)),
            ],
            options={
                'ordering': ['common_code'],
            },
        ),
    ]
