# Generated by Django 3.2.5 on 2023-01-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20230118_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cc2',
            name='created_user',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='cc2',
            name='modified_user',
            field=models.CharField(default='', max_length=11),
        ),
    ]
