version: '3.2'
services:
  nginx:
    image: nginx
    container_name: hrm_nginx
    restart: always
    volumes:
      - type: volume
        source: static_hrm
        target: /static
      - type: volume
        source: media_hrm
        target: /media
      - type: bind
        source: ./.conf/nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    depends_on:
      - hrm_web
    ports:
      - "80:80"
    networks:
      - hrm_network

  hrm_web:
    container_name: hrm_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
      - static_hrm:/static/
      - media_hrm:/app/media/

    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    restart: always
networks:
  defalut:
    external:
      name: hrm_network

volumes:
  static_hrm:
  media_hrm: