version: '3.2'
services:

  web:
    container_name: hrm_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static:/static/
      - media:/media/
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    restart: always

  nginx:
    image: nginx
    container_name: hrm_nginx
    restart: always
    volumes:
      - type: volume
        source: ./static
        target: /static
      - type: volume
        source: ./media
        target: /media
      - type: bind
        source: ./.conf/nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static:
  media: