version: '3.2'
services:
  web:
    container_name: hrm_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_hrm:/static/
      - media_hrm:/app/media/

    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    restart: always
networks:
  defalut:
    external:
      name: hrm_network
