# Generated by Django 3.2.5 on 2023-02-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EusoMem',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='아이디')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='로그인ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='비밀번호')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='이메일')),
                ('name', models.CharField(max_length=50, verbose_name='사원명')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='시스템관리자 여부')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('posi_cd', models.CharField(blank=True, max_length=20, null=True)),
                ('duty_resp_cd', models.CharField(blank=True, max_length=20, null=True)),
                ('dept_no', models.IntegerField(blank=True, db_column='dept_no', null=True)),
                ('zip_no', models.CharField(blank=True, max_length=50, null=True)),
                ('mem_addr', models.CharField(blank=True, max_length=100, null=True)),
                ('join_dt', models.CharField(blank=True, max_length=8, null=True)),
                ('mem_stat_cd', models.CharField(blank=True, max_length=20, null=True, verbose_name='회원상태코드')),
                ('reg_mem_no', models.IntegerField(blank=True, null=True)),
                ('modf_mem_no', models.IntegerField(blank=True, null=True)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('modf_dt', models.DateTimeField(auto_now=True, null=True)),
                ('del_yn', models.CharField(blank=True, default='N', max_length=1, null=True, verbose_name='삭제여부')),
                ('is_staff', models.BooleanField(default=False, verbose_name='시스템관리자 여부')),
            ],
            options={
                'db_table': 'euso_mem',
                'ordering': ['-join_dt'],
                'managed': False,
            },
        ),
    ]
