# Generated by Django 3.2.5 on 2023-01-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eusomem',
            name='del_yn',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='eusomem',
            name='modf_dt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='eusomem',
            name='reg_dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
