# Generated by Django 3.2.5 on 2023-01-27 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230125_1737'),
        ('accounts', '0002_auto_20230126_2013'),
    ]

    operations = [
    ]
